import type { AppLanguage } from "./LanguageContext";

const en = {
  mainNavigation: "Main navigation", mobileNavigation: "Mobile navigation", nowPlaying: "Now playing", hourShort: "h", minuteShort: "min", podcastCover: "cover", podcast: "Podcast", uniqueVisitors: "unique visitors recorded since analytics was enabled",
  analyticsConsent: "Analytics consent", analyticsBody: "Radiogram uses optional Google Analytics to understand website traffic and improve the experience. No analytics loads unless you accept.", seeOur: "See our", decline: "Decline", acceptAnalytics: "Accept analytics",
  pageNotFound: "Oops! Page not found", returnHome: "Return to Home", findingStation: "Finding the station…", stationNotFound: "Station not found", stationUnavailableBody: "This station may have moved or stopped broadcasting.", allStations: "All stations", liveFrom: "Live from", liveStream: "Live stream", listenLive: "Listen live", share: "Share", website: "Website", takeItWithYou: "Take it with you", moreListeningApp: "More listening in the Radiogram app.", stationAppBody: "Save favorite stations, recognize songs, keep your history, and listen with native Lock Screen controls on iPhone, iPad, and Mac.", keepExploring: "Keep exploring", moreFrom: "More from", seeAll: "See all",
  loadingEpisodes: "Loading episodes…", podcastNotFound: "Podcast not found", podcastUnavailableBody: "The show may no longer be available in this storefront.", browsePodcasts: "Browse podcasts", podcastSearch: "Podcast search", viewOnApplePodcasts: "View on Apple Podcasts", fullEpisodes: "Full episodes", episodes: "episodes", episodeSort: "Episode order", newestFirst: "Newest first", oldestFirst: "Oldest first", loadMoreEpisodes: "Load more episodes", noPlayableEpisodes: "No playable episodes", noPlayableEpisodesBody: "This show does not expose episodes through the web catalog.",
  applePodcastsUnavailable: "Apple Podcasts is unavailable right now. Please try again shortly.", podcastStorefront: "Podcast storefront", countryUS: "United States", countryGB: "United Kingdom", countryCA: "Canada", countryAU: "Australia", countryDE: "Germany", countryFR: "France", countryPL: "Poland", countryUA: "Ukraine", countryES: "Spain", countryIT: "Italy", countryJP: "Japan", countryCN: "China", dailyNews: "daily news", technology: "technology", history: "history", science: "science", comedy: "comedy", trueCrime: "true crime", music: "music", business: "business",
  slide01: "Find your station", slide02: "Search every match", slide03: "Identify any track", slide04: "Swipe between stations", slide05: "Dismiss the player naturally", slide06: "Discover podcasts", slide07: "Keep every favorite", slide08: "Choose your layout", slide09: "Let chance choose", slide10: "Control the Lock Screen", slide11: "Launch from Control Center", slide12: "Pick your widget", slide13: "Use quick actions", slide14: "Listen in your language",
  supportCenter: "Support Center", supportHeroBody: "Worldwide internet radio for iPhone, iPad, and Mac.", contactSupport: "Contact Support", browseFaq: "Browse FAQ", needHelp: "Need help or found a bug?", smallTeamBody: "We're a small independent team and we read every message. Pick the best channel below — we usually reply within", oneToThreeDays: "1–3 days", bugReports: "Bug Reports", somethingWrong: "Something not working?", bugReportBody: "Send us details about the issue, your device model, OS version, and what you were doing so we can reproduce and fix it fast.", businessInquiries: "Business Inquiries", partnershipsPress: "Partnerships & press", businessBody: "For collaborations, licensing, station partnerships, and media requests, get in touch via email.", averageResponse: "Average response time: 1–3 business days", supportDevelopment: "Support development", keepGrowing: "Help us keep Radiogram growing", supportDevelopmentBody: "Radiogram is built by a small independent team. If you enjoy the app, you can support its development or follow HP Games Lab for updates.", frequentlyAsked: "Frequently asked questions",
  supportPatreon: "Support on Patreon", supportPatreonAria: "Support HP Games Lab on Patreon", supportPatreonBody: "Support HP Games Lab with a recurring membership.", supportKofi: "Support on Ko-fi", supportKofiAria: "Support HP Games Lab on Ko-fi", supportKofiBody: "Make a one-time donation to support Radiogram development.", followTwitter: "Follow on Twitter", followTwitterAria: "Follow @hpgameslab on Twitter", followTwitterBody: "Follow @hpgameslab for Radiogram news and development updates.", followIndieHackers: "Follow on Indie Hackers", followIndieHackersAria: "Follow hpgameslab on Indie Hackers", followIndieHackersBody: "Follow the HP Games Lab journey and behind-the-scenes progress.",
  faq1Q: "How do I report a station issue?", faq1A: "Email us at {email} with the station name, stream URL if available, and a short description. We review every report.", faq2Q: "How can a station owner or rights holder request a correction or removal?", faq2A: "Email {email} with the station name, listing details, requested action, and information showing your relationship to the station or content. We will review the request and respond by email.", faq3Q: "How do I restore purchases?", faq3A: "Open Radiogram, go to Settings, and tap ‘Restore Purchases’. Make sure you are signed in with the same Apple ID used for the original purchase.", faq4Q: "Why is a station unavailable?", faq4A: "Stations sometimes go offline or change their stream URL without notice. If a station stays down for more than a few hours, please let us know and we'll update it.", faq5Q: "How do I suggest a feature?", faq5A: "We love feedback. Send your ideas to {email} — every email is read by a human, and many features come directly from listener suggestions.",
  streamPlaybackError: "This stream could not be played in the browser. Try another station or open it in Radiogram.", playbackBlocked: "Your browser blocked playback. Press play once more to start listening.", resumeError: "Unable to resume this stream.", bugEmailSubject: "Radiogram — Bug Report", businessEmailSubject: "Radiogram — Business Inquiry", faqLabel: "FAQ", jazz: "Jazz", news: "News", soul: "Soul", untitledEpisode: "Untitled episode", homeSeoTitle: "Radiogram — live radio and podcasts from around the world", homeSeoDescription: "Listen to thousands of live radio stations and discover podcasts online. Get Radiogram for iPhone, iPad, and Mac.", podcastsSeoTitle: "Discover podcasts and episodes | Radiogram", podcastsSeoDescription: "Search podcasts, browse shows, and listen to episodes online in Radiogram.", radioStationsIn: "Radio stations in", radioStations: "radio stations", radioSeoTitle: "Live radio stations from around the world | Radiogram", listenStationsFrom: "Listen to live internet radio stations from", browseStreams: "Browse streams by popularity, name, genre, and language in Radiogram.", listenPopular: "Listen to popular", radioOnlineFree: "radio stations online for free.", discoverStreams: "Discover live worldwide streams in Radiogram.", listenOnline: "listen online", stationSeoTitle: "Live radio station | Radiogram", listenTo: "Listen to", freeOnlineRadio: "Free online radio in Radiogram.", stationSeoDescription: "Listen to this live internet radio station free in Radiogram.", podcastEpisodes: "podcast episodes", podcastSeoTitle: "Podcast episodes | Radiogram",
  beijing: "Beijing", kyiv: "Kyiv", washington: "Washington",
};

type ExtraKey = keyof typeof en;
type ExtraDictionary = Record<ExtraKey, string>;

const ru: ExtraDictionary = {
  mainNavigation: "Основная навигация", mobileNavigation: "Мобильная навигация", nowPlaying: "Сейчас играет", hourShort: "ч", minuteShort: "мин", podcastCover: "обложка", podcast: "Подкаст", uniqueVisitors: "уникальных посетителей с момента включения аналитики",
  analyticsConsent: "Согласие на аналитику", analyticsBody: "Radiogram использует необязательную Google Analytics, чтобы понимать посещаемость сайта и улучшать его. Аналитика не загружается без вашего согласия.", seeOur: "Смотрите нашу", decline: "Отказаться", acceptAnalytics: "Разрешить аналитику",
  pageNotFound: "Страница не найдена", returnHome: "Вернуться на главную", findingStation: "Ищем станцию…", stationNotFound: "Станция не найдена", stationUnavailableBody: "Возможно, станция переехала или прекратила вещание.", allStations: "Все станции", liveFrom: "В эфире из", liveStream: "Прямой эфир", listenLive: "Слушать эфир", share: "Поделиться", website: "Сайт", takeItWithYou: "Возьми с собой", moreListeningApp: "Больше возможностей в приложении Radiogram.", stationAppBody: "Сохраняй станции, распознавай песни, веди историю и управляй прослушиванием с экрана блокировки на iPhone, iPad и Mac.", keepExploring: "Продолжай исследовать", moreFrom: "Ещё из", seeAll: "Показать все",
  loadingEpisodes: "Загружаем выпуски…", podcastNotFound: "Подкаст не найден", podcastUnavailableBody: "Возможно, этот подкаст больше недоступен в выбранном каталоге.", browsePodcasts: "Смотреть подкасты", podcastSearch: "Поиск подкастов", viewOnApplePodcasts: "Открыть в Apple Podcasts", fullEpisodes: "Все выпуски", episodes: "выпусков", episodeSort: "Порядок выпусков", newestFirst: "Сначала новые", oldestFirst: "Сначала старые", loadMoreEpisodes: "Загрузить ещё выпуски", noPlayableEpisodes: "Нет доступных выпусков", noPlayableEpisodesBody: "Этот подкаст не предоставляет выпуски через веб-каталог.",
  applePodcastsUnavailable: "Apple Podcasts сейчас недоступен. Попробуйте ещё раз чуть позже.", podcastStorefront: "Каталог подкастов", countryUS: "США", countryGB: "Великобритания", countryCA: "Канада", countryAU: "Австралия", countryDE: "Германия", countryFR: "Франция", countryPL: "Польша", countryUA: "Украина", countryES: "Испания", countryIT: "Италия", countryJP: "Япония", countryCN: "Китай", dailyNews: "новости дня", technology: "технологии", history: "история", science: "наука", comedy: "комедия", trueCrime: "настоящие преступления", music: "музыка", business: "бизнес",
  slide01: "Найди свою станцию", slide02: "Ищи по всем совпадениям", slide03: "Распознай любую песню", slide04: "Переключай станции свайпом", slide05: "Закрывай плеер естественным жестом", slide06: "Открывай подкасты", slide07: "Сохраняй избранное", slide08: "Выбирай вид", slide09: "Доверь выбор случаю", slide10: "Управляй с экрана блокировки", slide11: "Запускай из Пункта управления", slide12: "Выбирай виджет", slide13: "Используй быстрые действия", slide14: "Слушай на своём языке",
  supportCenter: "Центр поддержки", supportHeroBody: "Интернет-радио со всего мира для iPhone, iPad и Mac.", contactSupport: "Связаться с поддержкой", browseFaq: "Частые вопросы", needHelp: "Нужна помощь или нашли ошибку?", smallTeamBody: "Мы небольшая независимая команда и читаем каждое сообщение. Выберите подходящий способ связи — обычно мы отвечаем в течение", oneToThreeDays: "1–3 дней", bugReports: "Сообщения об ошибках", somethingWrong: "Что-то не работает?", bugReportBody: "Опишите проблему, модель устройства, версию ОС и свои действия, чтобы мы могли быстро воспроизвести и исправить ошибку.", businessInquiries: "Деловые запросы", partnershipsPress: "Партнёрства и пресса", businessBody: "По вопросам сотрудничества, лицензирования, партнёрств со станциями и СМИ напишите нам.", averageResponse: "Среднее время ответа: 1–3 рабочих дня", supportDevelopment: "Поддержать разработку", keepGrowing: "Помоги Radiogram развиваться", supportDevelopmentBody: "Radiogram создаёт небольшая независимая команда. Если вам нравится приложение, поддержите разработку или подпишитесь на новости HP Games Lab.", frequentlyAsked: "Частые вопросы",
  supportPatreon: "Поддержать на Patreon", supportPatreonAria: "Поддержать HP Games Lab на Patreon", supportPatreonBody: "Поддерживайте HP Games Lab регулярной подпиской.", supportKofi: "Поддержать на Ko-fi", supportKofiAria: "Поддержать HP Games Lab на Ko-fi", supportKofiBody: "Сделайте разовое пожертвование на развитие Radiogram.", followTwitter: "Подписаться в Twitter", followTwitterAria: "Подписаться на @hpgameslab в Twitter", followTwitterBody: "Следите за новостями и разработкой Radiogram.", followIndieHackers: "Подписаться на Indie Hackers", followIndieHackersAria: "Подписаться на hpgameslab в Indie Hackers", followIndieHackersBody: "Следите за развитием HP Games Lab и узнавайте, что происходит за кулисами.",
  faq1Q: "Как сообщить о проблеме со станцией?", faq1A: "Напишите на {email}, указав название станции, URL потока, если он известен, и краткое описание. Мы проверяем каждое сообщение.", faq2Q: "Как владельцу станции или правообладателю запросить исправление или удаление?", faq2A: "Напишите на {email}, указав станцию, данные каталога, требуемое действие и подтверждение вашей связи со станцией или контентом. Мы рассмотрим запрос и ответим по электронной почте.", faq3Q: "Как восстановить покупки?", faq3A: "Откройте Radiogram, перейдите в настройки и нажмите «Восстановить покупки». Убедитесь, что вошли с тем же Apple ID, который использовался при покупке.", faq4Q: "Почему станция недоступна?", faq4A: "Станции иногда отключаются или меняют адрес потока без предупреждения. Если станция недоступна несколько часов, сообщите нам — мы обновим её.", faq5Q: "Как предложить новую функцию?", faq5A: "Мы ценим отзывы. Отправьте идею на {email} — каждое письмо читает человек, и многие функции появились благодаря слушателям.",
  streamPlaybackError: "Не удалось воспроизвести этот поток в браузере. Попробуйте другую станцию или откройте её в Radiogram.", playbackBlocked: "Браузер заблокировал воспроизведение. Нажмите кнопку ещё раз.", resumeError: "Не удалось продолжить воспроизведение.", bugEmailSubject: "Radiogram — сообщение об ошибке", businessEmailSubject: "Radiogram — деловой запрос", faqLabel: "Вопросы и ответы", jazz: "Джаз", news: "Новости", soul: "Соул", untitledEpisode: "Выпуск без названия", homeSeoTitle: "Radiogram — радио и подкасты со всего мира", homeSeoDescription: "Слушайте тысячи радиостанций и открывайте подкасты онлайн. Скачайте Radiogram для iPhone, iPad и Mac.", podcastsSeoTitle: "Подкасты и выпуски | Radiogram", podcastsSeoDescription: "Ищите подкасты, открывайте шоу и слушайте выпуски онлайн в Radiogram.", radioStationsIn: "Радиостанции в", radioStations: "радиостанции", radioSeoTitle: "Радиостанции со всего мира | Radiogram", listenStationsFrom: "Слушайте интернет-радиостанции из", browseStreams: "Выбирайте эфиры по популярности, названию, жанру и языку в Radiogram.", listenPopular: "Слушайте популярные", radioOnlineFree: "радиостанции бесплатно онлайн.", discoverStreams: "Открывайте прямые эфиры со всего мира в Radiogram.", listenOnline: "слушать онлайн", stationSeoTitle: "Радиостанция в прямом эфире | Radiogram", listenTo: "Слушайте", freeOnlineRadio: "Бесплатное онлайн-радио в Radiogram.", stationSeoDescription: "Слушайте эту интернет-радиостанцию бесплатно в Radiogram.", podcastEpisodes: "выпуски подкаста", podcastSeoTitle: "Выпуски подкаста | Radiogram",
  beijing: "Пекин", kyiv: "Киев", washington: "Вашингтон",
};

const uk: ExtraDictionary = {
  ...ru,
  beijing: "Пекін", kyiv: "Київ", washington: "Вашингтон",
  slide01: "Знайди свою станцію", slide02: "Шукай усі збіги", slide03: "Розпізнай будь-яку пісню", slide04: "Перемикай станції свайпом", slide05: "Закривай плеєр природним жестом", slide06: "Відкривай подкасти", slide07: "Зберігай улюблене", slide08: "Обирай вигляд", slide09: "Довір вибір випадку", slide10: "Керуй з екрана блокування", slide11: "Запускай із Центру керування", slide12: "Обирай віджет", slide13: "Використовуй швидкі дії", slide14: "Слухай своєю мовою",
  supportPatreon: "Підтримати на Patreon", supportPatreonAria: "Підтримати HP Games Lab на Patreon", supportPatreonBody: "Підтримуйте HP Games Lab регулярною підпискою.", supportKofi: "Підтримати на Ko-fi", supportKofiAria: "Підтримати HP Games Lab на Ko-fi", supportKofiBody: "Зробіть разовий внесок у розвиток Radiogram.", followTwitter: "Підписатися у Twitter", followTwitterAria: "Підписатися на @hpgameslab у Twitter", followTwitterBody: "Стежте за новинами й розробкою Radiogram.", followIndieHackers: "Підписатися на Indie Hackers", followIndieHackersAria: "Підписатися на hpgameslab в Indie Hackers", followIndieHackersBody: "Стежте за розвитком HP Games Lab і закулісним прогресом.",
  mainNavigation: "Основна навігація", mobileNavigation: "Мобільна навігація", nowPlaying: "Зараз грає", hourShort: "год", minuteShort: "хв", podcastCover: "обкладинка", uniqueVisitors: "унікальних відвідувачів від часу ввімкнення аналітики",
  analyticsConsent: "Згода на аналітику", analyticsBody: "Radiogram використовує необов’язкову Google Analytics, щоб розуміти відвідуваність і покращувати сайт. Аналітика не завантажується без вашої згоди.", seeOur: "Перегляньте нашу", decline: "Відмовитися", acceptAnalytics: "Дозволити аналітику",
  pageNotFound: "Сторінку не знайдено", returnHome: "Повернутися на головну", findingStation: "Шукаємо станцію…", stationNotFound: "Станцію не знайдено", stationUnavailableBody: "Можливо, станція переїхала або припинила мовлення.", allStations: "Усі станції", liveFrom: "В ефірі з", liveStream: "Прямий ефір", listenLive: "Слухати ефір", share: "Поділитися", website: "Сайт", takeItWithYou: "Візьми із собою", moreListeningApp: "Більше можливостей у застосунку Radiogram.", stationAppBody: "Зберігай станції, розпізнавай пісні, веди історію та керуй прослуховуванням з екрана блокування на iPhone, iPad і Mac.", keepExploring: "Продовжуй досліджувати", moreFrom: "Ще з", seeAll: "Показати всі",
  loadingEpisodes: "Завантажуємо випуски…", podcastNotFound: "Подкаст не знайдено", podcastUnavailableBody: "Можливо, цей подкаст більше недоступний у вибраному каталозі.", browsePodcasts: "Переглянути подкасти", podcastSearch: "Пошук подкастів", viewOnApplePodcasts: "Відкрити в Apple Podcasts", fullEpisodes: "Усі випуски", episodes: "випусків", episodeSort: "Порядок випусків", newestFirst: "Спочатку нові", oldestFirst: "Спочатку старі", loadMoreEpisodes: "Завантажити ще випуски", noPlayableEpisodes: "Немає доступних випусків", noPlayableEpisodesBody: "Цей подкаст не надає випуски через вебкаталог.",
  applePodcastsUnavailable: "Apple Podcasts зараз недоступний. Спробуйте трохи пізніше.", podcastStorefront: "Каталог подкастів", countryUS: "США", countryGB: "Велика Британія", countryCA: "Канада", countryAU: "Австралія", countryDE: "Німеччина", countryFR: "Франція", countryPL: "Польща", countryUA: "Україна", countryES: "Іспанія", countryIT: "Італія", countryJP: "Японія", countryCN: "Китай", dailyNews: "новини дня", technology: "технології", history: "історія", science: "наука", comedy: "комедія", trueCrime: "справжні злочини", music: "музика", business: "бізнес",
  supportCenter: "Центр підтримки", supportHeroBody: "Інтернет-радіо з усього світу для iPhone, iPad і Mac.", contactSupport: "Зв’язатися з підтримкою", browseFaq: "Часті запитання", needHelp: "Потрібна допомога або знайшли помилку?", smallTeamBody: "Ми невелика незалежна команда й читаємо кожне повідомлення. Оберіть зручний спосіб зв’язку — зазвичай відповідаємо протягом", oneToThreeDays: "1–3 днів", bugReports: "Повідомлення про помилки", somethingWrong: "Щось не працює?", bugReportBody: "Опишіть проблему, модель пристрою, версію ОС і свої дії, щоб ми могли швидко відтворити та виправити помилку.", businessInquiries: "Ділові запити", partnershipsPress: "Партнерства та преса", businessBody: "Щодо співпраці, ліцензування, партнерств зі станціями та запитів ЗМІ напишіть нам.", averageResponse: "Середній час відповіді: 1–3 робочі дні", supportDevelopment: "Підтримати розробку", keepGrowing: "Допоможи Radiogram розвиватися", supportDevelopmentBody: "Radiogram створює невелика незалежна команда. Якщо вам подобається застосунок, підтримайте розробку або стежте за новинами HP Games Lab.", frequentlyAsked: "Часті запитання",
  faq1Q: "Як повідомити про проблему зі станцією?", faq1A: "Напишіть на {email}, зазначивши назву станції, URL потоку, якщо він відомий, і короткий опис. Ми перевіряємо кожне повідомлення.", faq2Q: "Як власнику станції або правовласнику запросити виправлення чи видалення?", faq2A: "Напишіть на {email}, зазначивши станцію, дані каталогу, потрібну дію та підтвердження вашого зв’язку зі станцією чи контентом. Ми розглянемо запит і відповімо електронною поштою.", faq3Q: "Як відновити покупки?", faq3A: "Відкрийте Radiogram, перейдіть у налаштування й натисніть «Відновити покупки». Увійдіть із тим самим Apple ID, який використовували для покупки.", faq4Q: "Чому станція недоступна?", faq4A: "Станції іноді вимикаються або змінюють адресу потоку без попередження. Якщо станція недоступна кілька годин, повідомте нам — ми її оновимо.", faq5Q: "Як запропонувати нову функцію?", faq5A: "Ми цінуємо відгуки. Надішліть ідею на {email} — кожен лист читає людина, а багато функцій з’явилися завдяки слухачам.",
  streamPlaybackError: "Не вдалося відтворити цей потік у браузері. Спробуйте іншу станцію або відкрийте її в Radiogram.", playbackBlocked: "Браузер заблокував відтворення. Натисніть кнопку ще раз.", resumeError: "Не вдалося продовжити відтворення.", bugEmailSubject: "Radiogram — повідомлення про помилку", businessEmailSubject: "Radiogram — діловий запит", faqLabel: "Запитання й відповіді", jazz: "Джаз", news: "Новини", soul: "Соул", untitledEpisode: "Випуск без назви",
  homeSeoTitle: "Radiogram — радіо й подкасти з усього світу", homeSeoDescription: "Слухайте тисячі радіостанцій і відкривайте подкасти онлайн. Завантажте Radiogram для iPhone, iPad і Mac.", podcastsSeoTitle: "Подкасти та випуски | Radiogram", podcastsSeoDescription: "Шукайте подкасти, відкривайте шоу та слухайте випуски онлайн у Radiogram.", radioStationsIn: "Радіостанції в", radioStations: "радіостанції", radioSeoTitle: "Радіостанції з усього світу | Radiogram", listenStationsFrom: "Слухайте інтернет-радіостанції з", browseStreams: "Обирайте ефіри за популярністю, назвою, жанром і мовою в Radiogram.", listenPopular: "Слухайте популярні", radioOnlineFree: "радіостанції безкоштовно онлайн.", discoverStreams: "Відкривайте прямі ефіри з усього світу в Radiogram.", listenOnline: "слухати онлайн", stationSeoTitle: "Радіостанція в прямому ефірі | Radiogram", listenTo: "Слухайте", freeOnlineRadio: "Безкоштовне онлайн-радіо в Radiogram.", stationSeoDescription: "Слухайте цю інтернет-радіостанцію безкоштовно в Radiogram.", podcastEpisodes: "випуски подкасту", podcastSeoTitle: "Випуски подкасту | Radiogram",
};

const pl: ExtraDictionary = {
  ...en,
  beijing: "Pekin", kyiv: "Kijów", washington: "Waszyngton",
  homeSeoTitle: "Radiogram — radio i podcasty z całego świata", homeSeoDescription: "Słuchaj tysięcy stacji i odkrywaj podcasty online. Pobierz Radiogram na iPhone’a, iPada i Maca.", podcastsSeoTitle: "Podcasty i odcinki | Radiogram", podcastsSeoDescription: "Wyszukuj podcasty, odkrywaj audycje i słuchaj odcinków online w Radiogram.", radioStationsIn: "Stacje radiowe w", radioStations: "stacje radiowe", radioSeoTitle: "Stacje radiowe z całego świata | Radiogram", listenStationsFrom: "Słuchaj internetowych stacji radiowych z", browseStreams: "Przeglądaj transmisje według popularności, nazwy, gatunku i języka w Radiogram.", listenPopular: "Słuchaj popularnych", radioOnlineFree: "stacji radiowych bezpłatnie online.", discoverStreams: "Odkrywaj transmisje na żywo z całego świata w Radiogram.", listenOnline: "słuchaj online", stationSeoTitle: "Stacja radiowa na żywo | Radiogram", listenTo: "Słuchaj", freeOnlineRadio: "Bezpłatne radio online w Radiogram.", stationSeoDescription: "Słuchaj tej internetowej stacji radiowej bezpłatnie w Radiogram.", podcastEpisodes: "odcinki podcastu", podcastSeoTitle: "Odcinki podcastu | Radiogram",
  slide01: "Znajdź swoją stację", slide02: "Przeszukaj wszystkie wyniki", slide03: "Rozpoznaj każdy utwór", slide04: "Przełączaj stacje gestem", slide05: "Naturalnie zamykaj odtwarzacz", slide06: "Odkrywaj podcasty", slide07: "Zachowaj ulubione", slide08: "Wybierz układ", slide09: "Pozwól zdecydować losowi", slide10: "Steruj z ekranu blokady", slide11: "Uruchamiaj z Centrum sterowania", slide12: "Wybierz widżet", slide13: "Używaj szybkich czynności", slide14: "Słuchaj w swoim języku",
  supportPatreon: "Wesprzyj na Patreon", supportPatreonAria: "Wesprzyj HP Games Lab na Patreon", supportPatreonBody: "Wspieraj HP Games Lab regularnym członkostwem.", supportKofi: "Wesprzyj na Ko-fi", supportKofiAria: "Wesprzyj HP Games Lab na Ko-fi", supportKofiBody: "Przekaż jednorazowe wsparcie na rozwój Radiogram.", followTwitter: "Obserwuj na Twitterze", followTwitterAria: "Obserwuj @hpgameslab na Twitterze", followTwitterBody: "Śledź wiadomości i rozwój Radiogram.", followIndieHackers: "Obserwuj na Indie Hackers", followIndieHackersAria: "Obserwuj hpgameslab na Indie Hackers", followIndieHackersBody: "Śledź drogę HP Games Lab i postępy zza kulis.", bugEmailSubject: "Radiogram — zgłoszenie błędu", businessEmailSubject: "Radiogram — zapytanie biznesowe", faqLabel: "FAQ", jazz: "Jazz", news: "Wiadomości", soul: "Soul", untitledEpisode: "Odcinek bez tytułu",
  mainNavigation: "Główna nawigacja", mobileNavigation: "Nawigacja mobilna", nowPlaying: "Teraz odtwarzane", hourShort: "godz.", minuteShort: "min", podcastCover: "okładka", uniqueVisitors: "unikalnych użytkowników od włączenia analityki", analyticsConsent: "Zgoda na analitykę", analyticsBody: "Radiogram opcjonalnie korzysta z Google Analytics, aby analizować ruch i ulepszać serwis. Analityka nie jest wczytywana bez Twojej zgody.", seeOur: "Zobacz naszą", decline: "Odrzuć", acceptAnalytics: "Akceptuj analitykę",
  pageNotFound: "Nie znaleziono strony", returnHome: "Wróć na stronę główną", findingStation: "Szukamy stacji…", stationNotFound: "Nie znaleziono stacji", stationUnavailableBody: "Stacja mogła zmienić adres lub zakończyć nadawanie.", allStations: "Wszystkie stacje", liveFrom: "Na żywo z", liveStream: "Transmisja na żywo", listenLive: "Słuchaj na żywo", share: "Udostępnij", website: "Strona", takeItWithYou: "Zabierz ze sobą", moreListeningApp: "Więcej możliwości w aplikacji Radiogram.", stationAppBody: "Zapisuj stacje, rozpoznawaj utwory, zachowuj historię i steruj z ekranu blokady na iPhonie, iPadzie i Macu.", keepExploring: "Odkrywaj dalej", moreFrom: "Więcej z", seeAll: "Zobacz wszystkie",
  loadingEpisodes: "Ładowanie odcinków…", podcastNotFound: "Nie znaleziono podcastu", podcastUnavailableBody: "Ten podcast może nie być już dostępny w wybranym katalogu.", browsePodcasts: "Przeglądaj podcasty", podcastSearch: "Wyszukiwanie podcastów", viewOnApplePodcasts: "Zobacz w Apple Podcasts", fullEpisodes: "Pełne odcinki", episodes: "odcinków", episodeSort: "Kolejność odcinków", newestFirst: "Najpierw najnowsze", oldestFirst: "Najpierw najstarsze", loadMoreEpisodes: "Wczytaj więcej odcinków", noPlayableEpisodes: "Brak dostępnych odcinków", noPlayableEpisodesBody: "Ten podcast nie udostępnia odcinków w katalogu internetowym.",
  applePodcastsUnavailable: "Apple Podcasts jest teraz niedostępny. Spróbuj ponownie za chwilę.", podcastStorefront: "Katalog podcastów", countryUS: "Stany Zjednoczone", countryGB: "Wielka Brytania", countryCA: "Kanada", countryAU: "Australia", countryDE: "Niemcy", countryFR: "Francja", countryPL: "Polska", countryUA: "Ukraina", countryES: "Hiszpania", countryIT: "Włochy", countryJP: "Japonia", countryCN: "Chiny", dailyNews: "wiadomości dnia", technology: "technologia", history: "historia", science: "nauka", comedy: "komedia", trueCrime: "prawdziwe zbrodnie", music: "muzyka", business: "biznes",
  supportCenter: "Centrum pomocy", supportHeroBody: "Światowe radio internetowe na iPhone’a, iPada i Maca.", contactSupport: "Skontaktuj się z pomocą", browseFaq: "Przeglądaj FAQ", needHelp: "Potrzebujesz pomocy lub znalazłeś błąd?", smallTeamBody: "Jesteśmy małym niezależnym zespołem i czytamy każdą wiadomość. Wybierz najlepszy kanał — zwykle odpowiadamy w ciągu", oneToThreeDays: "1–3 dni", bugReports: "Zgłoszenia błędów", somethingWrong: "Coś nie działa?", bugReportBody: "Opisz problem, model urządzenia, wersję systemu i wykonywane czynności, abyśmy mogli szybko odtworzyć i naprawić błąd.", businessInquiries: "Zapytania biznesowe", partnershipsPress: "Partnerstwa i prasa", businessBody: "W sprawie współpracy, licencji, partnerstw ze stacjami i mediów napisz do nas.", averageResponse: "Średni czas odpowiedzi: 1–3 dni robocze", supportDevelopment: "Wesprzyj rozwój", keepGrowing: "Pomóż rozwijać Radiogram", supportDevelopmentBody: "Radiogram tworzy mały niezależny zespół. Jeśli lubisz aplikację, wesprzyj jej rozwój lub obserwuj HP Games Lab.", frequentlyAsked: "Najczęściej zadawane pytania",
  faq1Q: "Jak zgłosić problem ze stacją?", faq1A: "Napisz na {email}, podając nazwę stacji, adres strumienia, jeśli jest dostępny, i krótki opis. Sprawdzamy każde zgłoszenie.", faq2Q: "Jak właściciel stacji lub praw zwraca się o poprawkę albo usunięcie?", faq2A: "Napisz na {email}, podając stację, dane wpisu, oczekiwane działanie i potwierdzenie związku ze stacją lub treścią. Rozpatrzymy zgłoszenie i odpowiemy e-mailem.", faq3Q: "Jak przywrócić zakupy?", faq3A: "Otwórz Radiogram, przejdź do Ustawień i wybierz „Przywróć zakupy”. Zaloguj się tym samym Apple ID co przy zakupie.", faq4Q: "Dlaczego stacja jest niedostępna?", faq4A: "Stacje czasem wyłączają się lub zmieniają adres bez ostrzeżenia. Jeśli problem trwa kilka godzin, daj nam znać — zaktualizujemy wpis.", faq5Q: "Jak zaproponować funkcję?", faq5A: "Cenimy opinie. Wyślij pomysł na {email} — każdą wiadomość czyta człowiek, a wiele funkcji pochodzi od słuchaczy.", streamPlaybackError: "Nie można odtworzyć tego strumienia w przeglądarce. Wybierz inną stację lub otwórz ją w Radiogram.", playbackBlocked: "Przeglądarka zablokowała odtwarzanie. Naciśnij odtwarzanie ponownie.", resumeError: "Nie można wznowić strumienia.",
};

const de: ExtraDictionary = {
  ...en,
  beijing: "Peking", kyiv: "Kyjiw", washington: "Washington",
  homeSeoTitle: "Radiogram — Radio und Podcasts aus aller Welt", homeSeoDescription: "Höre Tausende Live-Sender und entdecke Podcasts online. Lade Radiogram für iPhone, iPad und Mac.", podcastsSeoTitle: "Podcasts und Folgen | Radiogram", podcastsSeoDescription: "Suche Podcasts, entdecke Sendungen und höre Folgen online in Radiogram.", radioStationsIn: "Radiosender in", radioStations: "Radiosender", radioSeoTitle: "Radiosender aus aller Welt | Radiogram", listenStationsFrom: "Höre Internetradiosender aus", browseStreams: "Durchsuche Streams nach Beliebtheit, Name, Genre und Sprache in Radiogram.", listenPopular: "Höre beliebte", radioOnlineFree: "Radiosender kostenlos online.", discoverStreams: "Entdecke Live-Streams aus aller Welt in Radiogram.", listenOnline: "online hören", stationSeoTitle: "Live-Radiosender | Radiogram", listenTo: "Höre", freeOnlineRadio: "Kostenloses Online-Radio in Radiogram.", stationSeoDescription: "Höre diesen Internetradiosender kostenlos in Radiogram.", podcastEpisodes: "Podcast-Folgen", podcastSeoTitle: "Podcast-Folgen | Radiogram",
  slide01: "Finde deinen Sender", slide02: "Durchsuche alle Treffer", slide03: "Erkenne jeden Song", slide04: "Wische zwischen Sendern", slide05: "Schließe den Player mit einer Geste", slide06: "Entdecke Podcasts", slide07: "Behalte deine Favoriten", slide08: "Wähle dein Layout", slide09: "Lass den Zufall entscheiden", slide10: "Steuere vom Sperrbildschirm", slide11: "Starte aus dem Kontrollzentrum", slide12: "Wähle dein Widget", slide13: "Nutze Schnellaktionen", slide14: "Höre in deiner Sprache",
  supportPatreon: "Auf Patreon unterstützen", supportPatreonAria: "HP Games Lab auf Patreon unterstützen", supportPatreonBody: "Unterstütze HP Games Lab mit einer regelmäßigen Mitgliedschaft.", supportKofi: "Auf Ko-fi unterstützen", supportKofiAria: "HP Games Lab auf Ko-fi unterstützen", supportKofiBody: "Unterstütze die Radiogram-Entwicklung mit einer einmaligen Spende.", followTwitter: "Auf Twitter folgen", followTwitterAria: "@hpgameslab auf Twitter folgen", followTwitterBody: "Folge den Neuigkeiten und der Entwicklung von Radiogram.", followIndieHackers: "Auf Indie Hackers folgen", followIndieHackersAria: "hpgameslab auf Indie Hackers folgen", followIndieHackersBody: "Verfolge den Weg von HP Games Lab und Fortschritte hinter den Kulissen.", bugEmailSubject: "Radiogram — Fehlermeldung", businessEmailSubject: "Radiogram — Geschäftsanfrage", faqLabel: "FAQ", jazz: "Jazz", news: "Nachrichten", soul: "Soul", untitledEpisode: "Unbenannte Folge",
  mainNavigation: "Hauptnavigation", mobileNavigation: "Mobile Navigation", nowPlaying: "Aktuelle Wiedergabe", hourShort: "Std.", minuteShort: "Min.", podcastCover: "Cover", uniqueVisitors: "einzelne Besucher seit Aktivierung der Analyse", analyticsConsent: "Einwilligung zur Analyse", analyticsBody: "Radiogram verwendet optional Google Analytics, um den Website-Verkehr zu verstehen und das Erlebnis zu verbessern. Ohne deine Zustimmung wird keine Analyse geladen.", seeOur: "Siehe unsere", decline: "Ablehnen", acceptAnalytics: "Analyse akzeptieren",
  pageNotFound: "Seite nicht gefunden", returnHome: "Zur Startseite", findingStation: "Sender wird gesucht…", stationNotFound: "Sender nicht gefunden", stationUnavailableBody: "Der Sender ist möglicherweise umgezogen oder sendet nicht mehr.", allStations: "Alle Sender", liveFrom: "Live aus", liveStream: "Live-Stream", listenLive: "Live hören", share: "Teilen", website: "Website", takeItWithYou: "Nimm es mit", moreListeningApp: "Mehr Hörmöglichkeiten in der Radiogram-App.", stationAppBody: "Speichere Sender, erkenne Songs, behalte deinen Verlauf und steuere vom Sperrbildschirm auf iPhone, iPad und Mac.", keepExploring: "Weiter entdecken", moreFrom: "Mehr aus", seeAll: "Alle anzeigen",
  loadingEpisodes: "Folgen werden geladen…", podcastNotFound: "Podcast nicht gefunden", podcastUnavailableBody: "Diese Sendung ist in diesem Katalog möglicherweise nicht mehr verfügbar.", browsePodcasts: "Podcasts entdecken", podcastSearch: "Podcast-Suche", viewOnApplePodcasts: "In Apple Podcasts ansehen", fullEpisodes: "Ganze Folgen", episodes: "Folgen", episodeSort: "Reihenfolge der Folgen", newestFirst: "Neueste zuerst", oldestFirst: "Älteste zuerst", loadMoreEpisodes: "Mehr Folgen laden", noPlayableEpisodes: "Keine abspielbaren Folgen", noPlayableEpisodesBody: "Diese Sendung stellt über den Webkatalog keine Folgen bereit.",
  applePodcastsUnavailable: "Apple Podcasts ist gerade nicht verfügbar. Bitte versuche es gleich noch einmal.", podcastStorefront: "Podcast-Katalog", countryUS: "Vereinigte Staaten", countryGB: "Vereinigtes Königreich", countryCA: "Kanada", countryAU: "Australien", countryDE: "Deutschland", countryFR: "Frankreich", countryPL: "Polen", countryUA: "Ukraine", countryES: "Spanien", countryIT: "Italien", countryJP: "Japan", countryCN: "China", dailyNews: "Tagesnachrichten", technology: "Technologie", history: "Geschichte", science: "Wissenschaft", comedy: "Comedy", trueCrime: "True Crime", music: "Musik", business: "Wirtschaft",
  supportCenter: "Support-Center", supportHeroBody: "Weltweites Internetradio für iPhone, iPad und Mac.", contactSupport: "Support kontaktieren", browseFaq: "FAQ ansehen", needHelp: "Brauchst du Hilfe oder hast du einen Fehler gefunden?", smallTeamBody: "Wir sind ein kleines unabhängiges Team und lesen jede Nachricht. Wähle den passenden Kontaktweg — meist antworten wir innerhalb von", oneToThreeDays: "1–3 Tagen", bugReports: "Fehlermeldungen", somethingWrong: "Funktioniert etwas nicht?", bugReportBody: "Sende uns Angaben zum Problem, Gerätemodell, Betriebssystem und deinen Schritten, damit wir es schnell nachvollziehen und beheben können.", businessInquiries: "Geschäftliche Anfragen", partnershipsPress: "Partnerschaften & Presse", businessBody: "Für Kooperationen, Lizenzen, Senderpartnerschaften und Medienanfragen erreichst du uns per E-Mail.", averageResponse: "Durchschnittliche Antwortzeit: 1–3 Werktage", supportDevelopment: "Entwicklung unterstützen", keepGrowing: "Hilf Radiogram zu wachsen", supportDevelopmentBody: "Radiogram wird von einem kleinen unabhängigen Team entwickelt. Unterstütze die Entwicklung oder folge HP Games Lab für Neuigkeiten.", frequentlyAsked: "Häufig gestellte Fragen",
  faq1Q: "Wie melde ich ein Problem mit einem Sender?", faq1A: "Schreibe an {email} mit Sendername, Stream-URL (falls vorhanden) und einer kurzen Beschreibung. Wir prüfen jede Meldung.", faq2Q: "Wie können Senderinhaber oder Rechteinhaber eine Korrektur oder Entfernung beantragen?", faq2A: "Schreibe an {email} mit Sendername, Eintragsdetails, gewünschter Maßnahme und einem Nachweis deiner Beziehung zum Sender oder Inhalt. Wir prüfen die Anfrage und antworten per E-Mail.", faq3Q: "Wie stelle ich Käufe wieder her?", faq3A: "Öffne Radiogram, gehe zu Einstellungen und tippe auf „Käufe wiederherstellen“. Verwende dieselbe Apple-ID wie beim ursprünglichen Kauf.", faq4Q: "Warum ist ein Sender nicht verfügbar?", faq4A: "Sender gehen manchmal offline oder ändern ihre Stream-URL. Bleibt ein Sender mehrere Stunden aus, informiere uns bitte — wir aktualisieren ihn.", faq5Q: "Wie schlage ich eine Funktion vor?", faq5A: "Wir freuen uns über Feedback. Sende Ideen an {email} — jede Nachricht wird gelesen, und viele Funktionen gehen auf Vorschläge von Hörern zurück.", streamPlaybackError: "Dieser Stream konnte im Browser nicht abgespielt werden. Probiere einen anderen Sender oder öffne ihn in Radiogram.", playbackBlocked: "Dein Browser hat die Wiedergabe blockiert. Drücke erneut auf Wiedergabe.", resumeError: "Der Stream konnte nicht fortgesetzt werden.",
};

const zhCN: ExtraDictionary = {
  ...en,
  beijing: "北京", kyiv: "基辅", washington: "华盛顿",
  homeSeoTitle: "Radiogram — 全球广播与播客", homeSeoDescription: "在线收听数千个直播电台并发现播客。获取适用于 iPhone、iPad 和 Mac 的 Radiogram。", podcastsSeoTitle: "播客与单集 | Radiogram", podcastsSeoDescription: "在 Radiogram 中搜索播客、浏览节目并在线收听单集。", radioStationsIn: "广播电台地区：", radioStations: "广播电台", radioSeoTitle: "全球直播电台 | Radiogram", listenStationsFrom: "收听来自以下地区的网络电台：", browseStreams: "在 Radiogram 中按热度、名称、类型和语言浏览直播流。", listenPopular: "收听热门", radioOnlineFree: "广播电台，免费在线收听。", discoverStreams: "在 Radiogram 中发现全球直播流。", listenOnline: "在线收听", stationSeoTitle: "直播电台 | Radiogram", listenTo: "收听", freeOnlineRadio: "Radiogram 免费在线广播。", stationSeoDescription: "在 Radiogram 中免费收听此网络电台。", podcastEpisodes: "播客单集", podcastSeoTitle: "播客单集 | Radiogram",
  bugEmailSubject: "Radiogram — 问题报告", businessEmailSubject: "Radiogram — 商务咨询", faqLabel: "常见问题", jazz: "爵士", news: "新闻", soul: "灵魂乐", untitledEpisode: "无标题单集",
  mainNavigation: "主导航", mobileNavigation: "移动端导航", nowPlaying: "正在播放", hourShort: "小时", minuteShort: "分钟", podcastCover: "封面", podcast: "播客", uniqueVisitors: "自启用分析以来的独立访客", analyticsConsent: "分析授权", analyticsBody: "Radiogram 可选择使用 Google Analytics 来了解网站流量并改善体验。未经你的同意，不会加载任何分析功能。", seeOur: "查看我们的", decline: "拒绝", acceptAnalytics: "允许分析",
  pageNotFound: "找不到页面", returnHome: "返回首页", findingStation: "正在查找电台…", stationNotFound: "找不到电台", stationUnavailableBody: "该电台可能已更改地址或停止广播。", allStations: "所有电台", liveFrom: "直播地区：", liveStream: "直播流", listenLive: "收听直播", share: "分享", website: "网站", takeItWithYou: "随身收听", moreListeningApp: "在 Radiogram App 中畅享更多内容。", stationAppBody: "收藏电台、识别歌曲、保存历史，并在 iPhone、iPad 和 Mac 的锁定屏幕上控制播放。", keepExploring: "继续探索", moreFrom: "更多来自", seeAll: "查看全部",
  loadingEpisodes: "正在加载单集…", podcastNotFound: "找不到播客", podcastUnavailableBody: "该节目可能已无法在此目录中获取。", browsePodcasts: "浏览播客", podcastSearch: "搜索播客", viewOnApplePodcasts: "在 Apple Podcasts 中查看", fullEpisodes: "完整单集", episodes: "个单集", episodeSort: "单集排序", newestFirst: "最新优先", oldestFirst: "最早优先", loadMoreEpisodes: "加载更多单集", noPlayableEpisodes: "没有可播放的单集", noPlayableEpisodesBody: "该节目未通过网页目录提供单集。",
  applePodcastsUnavailable: "Apple Podcasts 暂时不可用，请稍后重试。", podcastStorefront: "播客地区目录", countryUS: "美国", countryGB: "英国", countryCA: "加拿大", countryAU: "澳大利亚", countryDE: "德国", countryFR: "法国", countryPL: "波兰", countryUA: "乌克兰", countryES: "西班牙", countryIT: "意大利", countryJP: "日本", countryCN: "中国", dailyNews: "每日新闻", technology: "科技", history: "历史", science: "科学", comedy: "喜剧", trueCrime: "真实罪案", music: "音乐", business: "商业",
  slide01: "寻找你的电台", slide02: "搜索所有匹配项", slide03: "识别任意歌曲", slide04: "滑动切换电台", slide05: "自然手势关闭播放器", slide06: "发现播客", slide07: "收藏喜爱的内容", slide08: "选择布局", slide09: "随机选择", slide10: "从锁定屏幕控制", slide11: "从控制中心启动", slide12: "选择小组件", slide13: "使用快捷操作", slide14: "用你的语言收听",
  supportCenter: "支持中心", supportHeroBody: "适用于 iPhone、iPad 和 Mac 的全球网络广播。", contactSupport: "联系支持", browseFaq: "浏览常见问题", needHelp: "需要帮助或发现了问题？", smallTeamBody: "我们是一支小型独立团队，会阅读每一条消息。请选择合适的联系渠道，我们通常会在", oneToThreeDays: "1–3 天内回复", bugReports: "问题报告", somethingWrong: "遇到无法正常工作的功能？", bugReportBody: "请提供问题详情、设备型号、系统版本和操作步骤，以便我们快速复现并修复。", businessInquiries: "商务咨询", partnershipsPress: "合作与媒体", businessBody: "如需合作、授权、电台合作或媒体咨询，请通过电子邮件联系我们。", averageResponse: "平均回复时间：1–3 个工作日", supportDevelopment: "支持开发", keepGrowing: "帮助 Radiogram 持续成长", supportDevelopmentBody: "Radiogram 由一支小型独立团队打造。如果你喜欢这款 App，可以支持开发或关注 HP Games Lab 获取更新。", frequentlyAsked: "常见问题",
  supportPatreon: "在 Patreon 上支持", supportPatreonAria: "在 Patreon 上支持 HP Games Lab", supportPatreonBody: "通过定期会员支持 HP Games Lab。", supportKofi: "在 Ko-fi 上支持", supportKofiAria: "在 Ko-fi 上支持 HP Games Lab", supportKofiBody: "一次性捐助 Radiogram 的开发。", followTwitter: "在 Twitter 上关注", followTwitterAria: "在 Twitter 上关注 @hpgameslab", followTwitterBody: "关注 Radiogram 新闻和开发动态。", followIndieHackers: "在 Indie Hackers 上关注", followIndieHackersAria: "在 Indie Hackers 上关注 hpgameslab", followIndieHackersBody: "关注 HP Games Lab 的历程和幕后进展。",
  faq1Q: "如何报告电台问题？", faq1A: "请发送邮件至 {email}，提供电台名称、可用的流地址和简短说明。我们会检查每一份报告。", faq2Q: "电台所有者或权利人如何申请更正或移除？", faq2A: "请发送邮件至 {email}，提供电台名称、目录信息、希望采取的操作以及你与电台或内容关系的证明。我们会审核并通过邮件回复。", faq3Q: "如何恢复购买？", faq3A: "打开 Radiogram，前往“设置”并点按“恢复购买”。请确保使用购买时的同一 Apple ID 登录。", faq4Q: "为什么电台不可用？", faq4A: "电台有时会离线或更改流地址。如果持续数小时无法使用，请告诉我们，我们会更新信息。", faq5Q: "如何建议新功能？", faq5A: "我们重视反馈。请将想法发送至 {email}，每封邮件都会由真人阅读，许多功能都来自听众建议。", streamPlaybackError: "无法在浏览器中播放此流。请尝试其他电台或在 Radiogram 中打开。", playbackBlocked: "浏览器阻止了播放，请再次按下播放按钮。", resumeError: "无法继续播放此流。",
};

export const extraTranslations: Record<AppLanguage, ExtraDictionary> = { en, ru, uk, pl, de, "zh-CN": zhCN };
