/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { readStorage, writeStorage } from "@/lib/storage";

export type AppLanguage = "en" | "ru" | "uk" | "pl" | "de";

export const appLanguages: Array<{ code: AppLanguage; label: string; short: string }> = [
  { code: "en", label: "English", short: "EN" },
  { code: "ru", label: "Русский", short: "RU" },
  { code: "uk", label: "Українська", short: "UK" },
  { code: "pl", label: "Polski", short: "PL" },
  { code: "de", label: "Deutsch", short: "DE" },
];

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    radio: "Radio", podcasts: "Podcasts", support: "Support", privacy: "Privacy Policy", terms: "Terms of Use", getApp: "Get Radiogram",
    listen: "Listen", liveRadio: "Live radio", helpLegal: "Help & legal", getInTouch: "Get in touch", radioData: "Radio data by Radio Browser", footerTagline: "The world’s radio and podcasts, on the web and every Apple screen.", curiousEars: "Made for curious ears.",
    liveWorld: "Live around the world", heroTitleA: "Turn the world", heroTitleB: "into your radio.", heroBody: "Thousands of live stations and podcasts, ready to play on the web. Take your favorites, song recognition, and listening history into the Radiogram app.", startListening: "Start listening", getTheApp: "Get the app", builtFor: "Built for",
    onAir: "On air now", popularStations: "Popular live stations", exploreAll: "Explore all", findFrequency: "Find your frequency", discoveryTitle: "A station for every version of you.", discoveryBody: "Search across countries, languages, genres, and tiny corners of the radio spectrum. From breaking news to deep house, public radio to late-night ambient.", openFinder: "Open the station finder", liveStations: "live stations", surprise: "Surprise me", spinWorld: "Spin the world", freshEpisodes: "Fresh episodes", podcastsWorth: "Podcasts worth hearing", searchPodcasts: "Search podcasts", fullExperience: "The full experience", remembered: "Your radio, remembered.", appBody: "Save stations, recognize the song that just played, build your listening history, and control playback from the Lock Screen.", favorites: "Station favorites", recognition: "Song recognition", nativeControls: "Native controls", download: "Download Radiogram", showcaseEyebrow: "Inside the app", showcaseTitle: "See Radiogram in action.", showcaseBody: "Search every station, recognize music, swipe between broadcasts, discover podcasts, and control listening across your Apple devices.", previousSlide: "Previous app screenshot", nextSlide: "Next app screenshot", tourEyebrow: "App tour", tourTitle: "Watch Radiogram in motion.", tourBody: "A short walkthrough of station search, music recognition, gestures, podcasts, widgets, and playback controls.", tourPlay: "Play video with sound", tourDuration: "1:46 with sound", tourYoutube: "Watch on YouTube",
    worldwide: "Worldwide stations", exploreRadio: "Explore live radio", catalogIntro: "Explore live radio from around the world. Search and filter thousands of stations by country, genre, popularity, and name.", searchStations: "Search stations", filters: "Filters", tags: "Tags", countries: "Countries", languages: "Languages", clear: "Clear", clearAll: "Clear all", resetFilters: "Reset all filters", findTag: "Find a tag", findCountry: "Find a country", findLanguage: "Find a language", all: "All", chooseThree: "choose up to 3", chooseOne: "choose one", fromDirectory: "from the directory", noTags: "No tags match this search.", noCountries: "No countries match this search.", noLanguages: "No languages match this search.", showMoreTags: "Show more tags", remaining: "remaining", featured: "Featured", popularNow: "Popular now", name: "Name", loaded: "stations loaded", tuning: "Tuning the dial…", lostSignal: "We lost the signal", catalogError: "The station directory is taking a break. Please try again in a moment.", tryAgain: "Try again", noStations: "No stations found", broaderSearch: "Try a broader search or clear one of the filters.", showAll: "Show all stations", loadMore: "Load more stations", resultsFor: "Results for", radioIn: "Radio in", browseCountry: "Browse by country", browseGenre: "Browse by genre", query: "Search",
    backToTop: "Back to top", interfaceLanguage: "Interface language", toggleMenu: "Toggle menu", sortStations: "Sort stations", displayMode: "Display mode", gridView: "Grid view", listView: "List view", activeFilters: "Active filters", browseCategories: "Browse radio categories",
    podcastCatalog: "Apple Podcasts catalog", findListen: "Find your next listen.", podcastIntro: "Search shows and play full podcast episodes without leaving Radiogram.", search: "Search", searchingPodcasts: "Searching podcasts…", couldntLoadPodcasts: "Couldn’t load podcasts", searchResults: "Search results", shows: "shows", clearSearch: "Clear search",
    play: "Play", pause: "Pause", volume: "Volume", closePlayer: "Close player", podcastEpisode: "Podcast episode", openStation: "Open", stationLogo: "logo", stationWebsite: "website",
  },
  ru: {
    radio: "Радио", podcasts: "Подкасты", support: "Поддержка", privacy: "Конфиденциальность", terms: "Условия использования", getApp: "Скачать Radiogram",
    listen: "Слушать", liveRadio: "Радиостанции", helpLegal: "Помощь и документы", getInTouch: "Связаться", radioData: "Данные Radio Browser", footerTagline: "Радио и подкасты со всего мира — в браузере и на устройствах Apple.", curiousEars: "Для любопытных слушателей.",
    liveWorld: "В прямом эфире по всему миру", heroTitleA: "Преврати весь мир", heroTitleB: "в своё радио.", heroBody: "Тысячи радиостанций и подкастов доступны прямо в браузере. Избранное, распознавание музыки и история прослушивания — в приложении Radiogram.", startListening: "Начать слушать", getTheApp: "Скачать приложение", builtFor: "Для",
    onAir: "Сейчас в эфире", popularStations: "Популярные станции", exploreAll: "Показать все", findFrequency: "Найди свою волну", discoveryTitle: "Станция для любого настроения.", discoveryBody: "Ищи по странам, языкам, жанрам и самым редким уголкам радиоэфира.", openFinder: "Открыть поиск станций", liveStations: "станций", surprise: "Удиви меня", spinWorld: "Случайная волна", freshEpisodes: "Свежие выпуски", podcastsWorth: "Подкасты, которые стоит услышать", searchPodcasts: "Искать подкасты", fullExperience: "Все возможности", remembered: "Твоё радио всё помнит.", appBody: "Сохраняй станции, распознавай музыку, веди историю и управляй воспроизведением с экрана блокировки.", favorites: "Избранные станции", recognition: "Распознавание музыки", nativeControls: "Системное управление", download: "Скачать Radiogram", showcaseEyebrow: "Внутри приложения", showcaseTitle: "Посмотри, как работает Radiogram.", showcaseBody: "Ищи станции, распознавай музыку, переключай эфиры свайпом, открывай подкасты и управляй прослушиванием на устройствах Apple.", previousSlide: "Предыдущий скриншот", nextSlide: "Следующий скриншот", tourEyebrow: "Обзор приложения", tourTitle: "Посмотри на Radiogram в движении.", tourBody: "Короткая демонстрация поиска станций, распознавания музыки, жестов, подкастов, виджетов и управления воспроизведением.", tourPlay: "Включить видео со звуком", tourDuration: "1:46 со звуком", tourYoutube: "Смотреть на YouTube",
    worldwide: "Станции со всего мира", exploreRadio: "Исследуй радиоэфир", catalogIntro: "Слушай радио со всего мира. Ищи и фильтруй тысячи станций по стране, жанру, популярности и названию.", searchStations: "Поиск станций", filters: "Фильтры", tags: "Теги", countries: "Страны", languages: "Языки", clear: "Очистить", clearAll: "Сбросить всё", resetFilters: "Сбросить все фильтры", findTag: "Найти тег", findCountry: "Найти страну", findLanguage: "Найти язык", all: "Все", chooseThree: "до 3 вариантов", chooseOne: "один вариант", fromDirectory: "в каталоге", noTags: "Теги не найдены.", noCountries: "Страны не найдены.", noLanguages: "Языки не найдены.", showMoreTags: "Показать ещё теги", remaining: "осталось", featured: "Рекомендуемые", popularNow: "Популярные", name: "По названию", loaded: "станций загружено", tuning: "Настраиваем волну…", lostSignal: "Сигнал потерян", catalogError: "Каталог станций временно недоступен. Попробуй ещё раз через минуту.", tryAgain: "Повторить", noStations: "Станции не найдены", broaderSearch: "Попробуй изменить запрос или убрать один из фильтров.", showAll: "Показать все станции", loadMore: "Загрузить ещё", resultsFor: "Результаты для", radioIn: "Радио в", browseCountry: "По странам", browseGenre: "По жанрам", query: "Поиск",
    backToTop: "Наверх", interfaceLanguage: "Язык интерфейса", toggleMenu: "Открыть меню", sortStations: "Сортировка станций", displayMode: "Вид списка", gridView: "Плитка", listView: "Список", activeFilters: "Активные фильтры", browseCategories: "Категории радио",
    podcastCatalog: "Каталог Apple Podcasts", findListen: "Найди, что послушать.", podcastIntro: "Ищи подкасты и слушай полные выпуски, не покидая Radiogram.", search: "Найти", searchingPodcasts: "Ищем подкасты…", couldntLoadPodcasts: "Не удалось загрузить подкасты", searchResults: "Результаты поиска", shows: "подкастов", clearSearch: "Очистить поиск",
    play: "Воспроизвести", pause: "Пауза", volume: "Громкость", closePlayer: "Закрыть плеер", podcastEpisode: "Выпуск подкаста", openStation: "Открыть", stationLogo: "логотип", stationWebsite: "сайт",
  },
  uk: {
    radio: "Радіо", podcasts: "Подкасти", support: "Підтримка", privacy: "Конфіденційність", terms: "Умови використання", getApp: "Завантажити Radiogram",
    listen: "Слухати", liveRadio: "Радіостанції", helpLegal: "Допомога та документи", getInTouch: "Зв’язатися", radioData: "Дані Radio Browser", footerTagline: "Радіо й подкасти з усього світу — у браузері та на пристроях Apple.", curiousEars: "Для допитливих слухачів.",
    liveWorld: "У прямому ефірі по всьому світу", heroTitleA: "Перетвори весь світ", heroTitleB: "на своє радіо.", heroBody: "Тисячі радіостанцій і подкастів доступні у браузері. Обране, розпізнавання музики та історія — у застосунку Radiogram.", startListening: "Почати слухати", getTheApp: "Завантажити застосунок", builtFor: "Для",
    onAir: "Зараз в ефірі", popularStations: "Популярні станції", exploreAll: "Показати всі", findFrequency: "Знайди свою хвилю", discoveryTitle: "Станція для кожного настрою.", discoveryBody: "Шукай за країнами, мовами, жанрами та найрідкіснішими куточками радіоефіру.", openFinder: "Відкрити пошук станцій", liveStations: "станцій", surprise: "Здивуй мене", spinWorld: "Випадкова хвиля", freshEpisodes: "Свіжі випуски", podcastsWorth: "Подкасти, які варто почути", searchPodcasts: "Шукати подкасти", fullExperience: "Усі можливості", remembered: "Твоє радіо все пам’ятає.", appBody: "Зберігай станції, розпізнавай музику, веди історію та керуй відтворенням з екрана блокування.", favorites: "Обрані станції", recognition: "Розпізнавання музики", nativeControls: "Системне керування", download: "Завантажити Radiogram", showcaseEyebrow: "Усередині застосунку", showcaseTitle: "Подивись, як працює Radiogram.", showcaseBody: "Шукай станції, розпізнавай музику, перемикай ефіри свайпом, відкривай подкасти та керуй прослуховуванням на пристроях Apple.", previousSlide: "Попередній скриншот", nextSlide: "Наступний скриншот", tourEyebrow: "Огляд застосунку", tourTitle: "Подивись на Radiogram у русі.", tourBody: "Коротка демонстрація пошуку станцій, розпізнавання музики, жестів, подкастів, віджетів і керування відтворенням.", tourPlay: "Увімкнути відео зі звуком", tourDuration: "1:46 зі звуком", tourYoutube: "Дивитися на YouTube",
    worldwide: "Станції з усього світу", exploreRadio: "Досліджуй радіоефір", catalogIntro: "Слухай радіо з усього світу. Шукай і фільтруй тисячі станцій за країною, жанром, популярністю та назвою.", searchStations: "Пошук станцій", filters: "Фільтри", tags: "Теги", countries: "Країни", languages: "Мови", clear: "Очистити", clearAll: "Скинути все", resetFilters: "Скинути всі фільтри", findTag: "Знайти тег", findCountry: "Знайти країну", findLanguage: "Знайти мову", all: "Усі", chooseThree: "до 3 варіантів", chooseOne: "один варіант", fromDirectory: "у каталозі", noTags: "Теги не знайдено.", noCountries: "Країни не знайдено.", noLanguages: "Мови не знайдено.", showMoreTags: "Показати ще теги", remaining: "залишилося", featured: "Рекомендовані", popularNow: "Популярні", name: "За назвою", loaded: "станцій завантажено", tuning: "Налаштовуємо хвилю…", lostSignal: "Сигнал втрачено", catalogError: "Каталог станцій тимчасово недоступний. Спробуй ще раз за хвилину.", tryAgain: "Повторити", noStations: "Станцій не знайдено", broaderSearch: "Спробуй змінити запит або прибрати один із фільтрів.", showAll: "Показати всі станції", loadMore: "Завантажити ще", resultsFor: "Результати для", radioIn: "Радіо в", browseCountry: "За країнами", browseGenre: "За жанрами", query: "Пошук",
    backToTop: "Вгору", interfaceLanguage: "Мова інтерфейсу", toggleMenu: "Відкрити меню", sortStations: "Сортування станцій", displayMode: "Вигляд списку", gridView: "Плитка", listView: "Список", activeFilters: "Активні фільтри", browseCategories: "Категорії радіо",
    podcastCatalog: "Каталог Apple Podcasts", findListen: "Знайди, що послухати.", podcastIntro: "Шукай подкасти та слухай повні випуски, не залишаючи Radiogram.", search: "Знайти", searchingPodcasts: "Шукаємо подкасти…", couldntLoadPodcasts: "Не вдалося завантажити подкасти", searchResults: "Результати пошуку", shows: "подкастів", clearSearch: "Очистити пошук",
    play: "Відтворити", pause: "Пауза", volume: "Гучність", closePlayer: "Закрити плеєр", podcastEpisode: "Випуск подкасту", openStation: "Відкрити", stationLogo: "логотип", stationWebsite: "сайт",
  },
  pl: {
    radio: "Radio", podcasts: "Podcasty", support: "Pomoc", privacy: "Prywatność", terms: "Warunki korzystania", getApp: "Pobierz Radiogram",
    listen: "Słuchaj", liveRadio: "Radio na żywo", helpLegal: "Pomoc i dokumenty", getInTouch: "Kontakt", radioData: "Dane Radio Browser", footerTagline: "Radio i podcasty z całego świata — w przeglądarce i na urządzeniach Apple.", curiousEars: "Dla ciekawych słuchaczy.",
    liveWorld: "Na żywo z całego świata", heroTitleA: "Zamień cały świat", heroTitleB: "w swoje radio.", heroBody: "Tysiące stacji radiowych i podcastów w przeglądarce. Ulubione, rozpoznawanie muzyki i historia czekają w aplikacji Radiogram.", startListening: "Zacznij słuchać", getTheApp: "Pobierz aplikację", builtFor: "Dla",
    onAir: "Teraz na antenie", popularStations: "Popularne stacje", exploreAll: "Zobacz wszystkie", findFrequency: "Znajdź swoją falę", discoveryTitle: "Stacja na każdy nastrój.", discoveryBody: "Szukaj według krajów, języków, gatunków i najdalszych zakątków eteru.", openFinder: "Otwórz wyszukiwarkę", liveStations: "stacji", surprise: "Zaskocz mnie", spinWorld: "Losowa fala", freshEpisodes: "Najnowsze odcinki", podcastsWorth: "Podcasty warte uwagi", searchPodcasts: "Szukaj podcastów", fullExperience: "Pełne możliwości", remembered: "Twoje radio pamięta.", appBody: "Zapisuj stacje, rozpoznawaj utwory, zachowuj historię i steruj z ekranu blokady.", favorites: "Ulubione stacje", recognition: "Rozpoznawanie muzyki", nativeControls: "Sterowanie systemowe", download: "Pobierz Radiogram", showcaseEyebrow: "Wewnątrz aplikacji", showcaseTitle: "Zobacz Radiogram w działaniu.", showcaseBody: "Wyszukuj stacje, rozpoznawaj muzykę, zmieniaj audycje gestem, odkrywaj podcasty i steruj słuchaniem na urządzeniach Apple.", previousSlide: "Poprzedni zrzut ekranu", nextSlide: "Następny zrzut ekranu", tourEyebrow: "Prezentacja aplikacji", tourTitle: "Zobacz Radiogram w ruchu.", tourBody: "Krótka prezentacja wyszukiwania stacji, rozpoznawania muzyki, gestów, podcastów, widżetów i sterowania odtwarzaniem.", tourPlay: "Odtwórz film z dźwiękiem", tourDuration: "1:46 z dźwiękiem", tourYoutube: "Obejrzyj na YouTube",
    worldwide: "Stacje z całego świata", exploreRadio: "Odkrywaj radio", catalogIntro: "Słuchaj radia z całego świata. Wyszukuj i filtruj tysiące stacji według kraju, gatunku, popularności i nazwy.", searchStations: "Szukaj stacji", filters: "Filtry", tags: "Tagi", countries: "Kraje", languages: "Języki", clear: "Wyczyść", clearAll: "Wyczyść wszystko", resetFilters: "Wyczyść wszystkie filtry", findTag: "Znajdź tag", findCountry: "Znajdź kraj", findLanguage: "Znajdź język", all: "Wszystkie", chooseThree: "maks. 3", chooseOne: "jeden wybór", fromDirectory: "w katalogu", noTags: "Nie znaleziono tagów.", noCountries: "Nie znaleziono krajów.", noLanguages: "Nie znaleziono języków.", showMoreTags: "Pokaż więcej tagów", remaining: "pozostało", featured: "Polecane", popularNow: "Popularne", name: "Nazwa", loaded: "załadowanych stacji", tuning: "Strojenie…", lostSignal: "Utracono sygnał", catalogError: "Katalog stacji jest chwilowo niedostępny. Spróbuj ponownie za moment.", tryAgain: "Spróbuj ponownie", noStations: "Nie znaleziono stacji", broaderSearch: "Zmień wyszukiwanie lub usuń jeden z filtrów.", showAll: "Pokaż wszystkie stacje", loadMore: "Załaduj więcej", resultsFor: "Wyniki dla", radioIn: "Radio w", browseCountry: "Według kraju", browseGenre: "Według gatunku", query: "Wyszukiwanie",
    backToTop: "Do góry", interfaceLanguage: "Język interfejsu", toggleMenu: "Otwórz menu", sortStations: "Sortowanie stacji", displayMode: "Widok wyników", gridView: "Kafelki", listView: "Lista", activeFilters: "Aktywne filtry", browseCategories: "Kategorie radia",
    podcastCatalog: "Katalog Apple Podcasts", findListen: "Znajdź coś dla siebie.", podcastIntro: "Szukaj audycji i słuchaj pełnych odcinków bez opuszczania Radiogram.", search: "Szukaj", searchingPodcasts: "Wyszukiwanie podcastów…", couldntLoadPodcasts: "Nie udało się wczytać podcastów", searchResults: "Wyniki wyszukiwania", shows: "podcastów", clearSearch: "Wyczyść wyszukiwanie",
    play: "Odtwórz", pause: "Pauza", volume: "Głośność", closePlayer: "Zamknij odtwarzacz", podcastEpisode: "Odcinek podcastu", openStation: "Otwórz", stationLogo: "logo", stationWebsite: "strona internetowa",
  },
  de: {
    radio: "Radio", podcasts: "Podcasts", support: "Support", privacy: "Datenschutz", terms: "Nutzungsbedingungen", getApp: "Radiogram laden",
    listen: "Hören", liveRadio: "Live-Radio", helpLegal: "Hilfe & Rechtliches", getInTouch: "Kontakt", radioData: "Radiodaten von Radio Browser", footerTagline: "Radio und Podcasts aus aller Welt — im Web und auf Apple-Geräten.", curiousEars: "Für neugierige Ohren.",
    liveWorld: "Live aus aller Welt", heroTitleA: "Mach die ganze Welt", heroTitleB: "zu deinem Radio.", heroBody: "Tausende Live-Sender und Podcasts im Web. Favoriten, Musikerkennung und Verlauf gibt es in der Radiogram-App.", startListening: "Jetzt hören", getTheApp: "App laden", builtFor: "Für",
    onAir: "Jetzt live", popularStations: "Beliebte Sender", exploreAll: "Alle entdecken", findFrequency: "Finde deine Frequenz", discoveryTitle: "Ein Sender für jede Stimmung.", discoveryBody: "Suche nach Ländern, Sprachen, Genres und in den kleinsten Ecken des Radiospektrums.", openFinder: "Sendersuche öffnen", liveStations: "Live-Sender", surprise: "Überrasch mich", spinWorld: "Zufälliger Sender", freshEpisodes: "Neue Folgen", podcastsWorth: "Hörenswerte Podcasts", searchPodcasts: "Podcasts suchen", fullExperience: "Das volle Erlebnis", remembered: "Dein Radio merkt sich alles.", appBody: "Speichere Sender, erkenne Songs, behalte deinen Verlauf und steuere alles vom Sperrbildschirm.", favorites: "Lieblingssender", recognition: "Musikerkennung", nativeControls: "Systemsteuerung", download: "Radiogram laden", showcaseEyebrow: "In der App", showcaseTitle: "Radiogram in Aktion.", showcaseBody: "Finde Sender, erkenne Musik, wechsle per Wischgeste, entdecke Podcasts und steuere die Wiedergabe auf deinen Apple-Geräten.", previousSlide: "Vorheriger Screenshot", nextSlide: "Nächster Screenshot", tourEyebrow: "App-Tour", tourTitle: "Erlebe Radiogram in Bewegung.", tourBody: "Ein kurzer Rundgang durch Sendersuche, Musikerkennung, Gesten, Podcasts, Widgets und Wiedergabesteuerung.", tourPlay: "Video mit Ton abspielen", tourDuration: "1:46 mit Ton", tourYoutube: "Auf YouTube ansehen",
    worldwide: "Sender aus aller Welt", exploreRadio: "Live-Radio entdecken", catalogIntro: "Höre Live-Radio aus aller Welt. Suche und filtere Tausende Sender nach Land, Genre, Beliebtheit und Name.", searchStations: "Sender suchen", filters: "Filter", tags: "Tags", countries: "Länder", languages: "Sprachen", clear: "Löschen", clearAll: "Alles löschen", resetFilters: "Alle Filter zurücksetzen", findTag: "Tag suchen", findCountry: "Land suchen", findLanguage: "Sprache suchen", all: "Alle", chooseThree: "bis zu 3", chooseOne: "eine Auswahl", fromDirectory: "im Verzeichnis", noTags: "Keine passenden Tags.", noCountries: "Keine passenden Länder.", noLanguages: "Keine passenden Sprachen.", showMoreTags: "Mehr Tags anzeigen", remaining: "übrig", featured: "Empfohlen", popularNow: "Jetzt beliebt", name: "Name", loaded: "Sender geladen", tuning: "Sender wird eingestellt…", lostSignal: "Signal verloren", catalogError: "Das Senderverzeichnis ist gerade nicht erreichbar. Versuche es gleich noch einmal.", tryAgain: "Erneut versuchen", noStations: "Keine Sender gefunden", broaderSearch: "Ändere die Suche oder entferne einen Filter.", showAll: "Alle Sender anzeigen", loadMore: "Mehr Sender laden", resultsFor: "Ergebnisse für", radioIn: "Radio in", browseCountry: "Nach Land", browseGenre: "Nach Genre", query: "Suche",
    backToTop: "Nach oben", interfaceLanguage: "Sprache der Oberfläche", toggleMenu: "Menü öffnen", sortStations: "Sender sortieren", displayMode: "Darstellung", gridView: "Raster", listView: "Liste", activeFilters: "Aktive Filter", browseCategories: "Radiokategorien",
    podcastCatalog: "Apple Podcasts-Katalog", findListen: "Finde dein nächstes Hörerlebnis.", podcastIntro: "Suche Sendungen und höre ganze Folgen, ohne Radiogram zu verlassen.", search: "Suchen", searchingPodcasts: "Podcasts werden gesucht…", couldntLoadPodcasts: "Podcasts konnten nicht geladen werden", searchResults: "Suchergebnisse", shows: "Sendungen", clearSearch: "Suche löschen",
    play: "Abspielen", pause: "Pause", volume: "Lautstärke", closePlayer: "Player schließen", podcastEpisode: "Podcast-Folge", openStation: "Öffnen", stationLogo: "Logo", stationWebsite: "Website",
  },
};

type LanguageContextValue = { language: AppLanguage; setLanguage: (language: AppLanguage) => void; t: (key: string) => string; locale: string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    const stored = readStorage<AppLanguage | null>("app.language", null);
    if (stored && appLanguages.some((item) => item.code === stored)) return stored;
    const browserLanguage = navigator.language.split("-")[0] as AppLanguage;
    return appLanguages.some((item) => item.code === browserLanguage) ? browserLanguage : "en";
  });
  const setLanguage = (next: AppLanguage) => { setLanguageState(next); writeStorage("app.language", next); };
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (key: string) => translations[language][key] || translations.en[key] || key, locale: language }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
};
